#!/bin/bash
read -p "Mode (lang or utils): " mode
read -p "Enter a $mode: " selected
read -p "Query: " query

if [ "$mode" == "lang" ]; then
    tmux neww bash -c "curl -s cht.sh/$selected/$(echo $query | sed 's/ /+/g') | less -R"
elif [ "$mode" == "utils" ]; then
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less -R"
fi
