#!/bin/bash

password=$(zenity --password --title="Mot de passe")
aescrypt -d -p $password $@ &> /dev/null && rm $@ || zenity --error --text="Une erreur s'est produite" --title "Erreur"
unset password
