#!/bin/bash

# ext - archive extractor
# usage: ext <file>

[ ! -f "$@" ] && echo "\"$1\" is not a valid file" && exit 1

case "$@" in
    *.tar.bz2)   tar xjf "$@"   ;;
    *.tar.gz)    tar xzf "$@"   ;;
    *.bz2)       bunzip2 "$@"   ;;
    *.rar)       unrar x "$@"     ;;
    *.gz)        gunzip "$@"    ;;
    *.tar)       tar xf "$@"    ;;
    *.tbz2)      tar xjf "$@"   ;;
    *.tgz)       tar xzf "$@"   ;;
    *.zip)       unzip "$@"     ;;
    *.Z)         uncompress "$@";;
    *.7z)        7z x "$@"      ;;
    *)           echo "\"$*\" cannot be extracted via ext()" ;;
esac
