#!/bin/bash

UID=$(id -u)
GID=$(id -g)
noUmountRegex="(/$|/boot|/home|/perso|/save)"

# info <msg>
function info() {
    [ "$1" == "" ] && exit 1
    # zenity --info --text="$1" --title="Info"
    notify-send "Info" "$1"
}

# error <msg>
function error() {
    [ "$1" == "" ] && exit 1
    # zenity --error --text="$1" --title="Error"
    notify-send "Error" "$1"
}

function helpFunc() {
    echo "Usage: $(basename $0) [options]

Option:
-h, --help .................... Show this help message and exit
--mount ....................... Mount the disk
--umount ...................... Unmount the disk"
}

function mountDisk() {
    mountable=$(lsblk -lp | \
        grep "part $" | \
        awk '{print $1, "(" $4 ")"}'
    )
    [ "$mountable" = "" ] && error "No mountable disks found" && exit 1

    diskToMount=$(echo -e "$mountable" | rofi -dmenu -p "Mount which disk" | awk '{print $1}')
    [ "$diskToMount" = "" ] && exit 1
    mountPoint=$(find /media -maxdepth 1 -type d 2> /dev/null | rofi -dmenu -p "Mount to which directory")
    [ "$mountPoint" = "" ] && exit 1

    [ ! -d $mountPoint ] && mkdir -p $mountPoint

    if sudo mount -o uid=$UID,gid=$GID $diskToMount $mountPoint 2> /dev/null; then
        info "Disk mounted to \"$mountPoint\""
    else
        error "Failed to mount disk"
        exit 1
    fi
}

function umountDisk() {
    mounted=$(lsblk -lp | \
        grep "part /" | \
        grep -Ev "$noUmountRegex" | \
        awk '{print $1, "(" $4 ")"}'
    )
    [ "$mounted" = "" ] && error "No mounted disks found" && exit 1

    diskToUmount=$(echo -e "$mounted" | rofi -dmenu -p "Umount which disk" | awk '{print $1}')
    [ "$diskToUmount" = "" ] && exit 1

    if sudo umount $diskToUmount 2> /dev/null; then
        info "Disk \"$diskToUmount\" unmounted"
    else
        error "Failed to unmount disk"
        exit 1
    fi
}

if [ $# -eq 1 ]; then
    case $1 in
        -h | --help)
            helpFunc
            exit 0 ;;
        --mount)
            mountDisk
            exit 0;;
        --umount)
            umountDisk
            exit 0;;
        *)
            error "Unknown paramater \"$1\""
            exit 1 ;;
    esac
fi

