#!/bin/bash
pulseaudio-control \
    --icons-volume "%{F#3498db}%{F-} ,%{F#3498db}%{F-} " \
    --icon-muted " " \
    --sink-nicknames-from "device.description" \
    --sink-nickname "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3:Speakers" \
    --sink-nickname "alsa_output.usb-SteelSeries_Arctis_7_-00.analog-stereo:%{F#3498db}%{F-} Casque" \
    --sink-nickname "alsa_output.pci-0000_00_1f.3.analog-stereo:Ecouteur" \
    listen
