#!/bin/bash
pulseaudio-control \
    --icons-volume "%{F#3498db}󰖀%{F-} ,%{F#3498db}󰕾%{F-} " \
    --icon-muted "󰕿 " \
    --node-nicknames-from "device.description" \
    --node-nickname "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3:%{F#3498db}󰓃%{F-} Speakers" \
    --node-nickname "alsa_output.usb-SteelSeries_Arctis_7_-00.analog-stereo:%{F#3498db}󰋋%{F-} Casque" \
    --node-nickname "alsa_output.pci-0000_00_1f.3.analog-stereo:%{F#3498db}󰓃%{F-} Ecouteur" \
    --node-nickname "bluez_output.84_D3_52_B0_99_E2.1:%{F#3498db}󰋋%{F-} Casque JBL" \
    listen
