#!/bin/bash
# --icons-volume "%{F#3498db}%{F-} ,%{F#3498db}%{F-} " \
# --icon-muted " " \
pulseaudio-control \
    --icons-volume "%{F#3498db}󰖀%{F-} ,%{F#3498db}󰕾%{F-} " \
    --icon-muted "󰕿 " \
    --node-nicknames-from "device.description" \
    --node-nickname "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3:%{F#3498db}󰓃%{F-} Speakers" \
    --node-nickname "alsa_output.usb-SteelSeries_Arctis_7_-00.analog-stereo:%{F#3498db}󰋋%{F-} Casque" \
    --node-nickname "alsa_output.pci-0000_00_1f.3.analog-stereo:%{F#3498db}󰓃%{F-} Ecouteur" \
    listen
