#!/bin/bash
# author : lordpax
# screen v1.3

ignoreScreen="None"
version="v1.3"
dependencies="rofi notify-send i3-msg xrandr awk grep seq"
presets="screenPresetWork\nscreenPresetStartup"

# info <msg>
function info() {
    [ -z "$1" ] && exit 1
    notify-send "Info" "$1"
}

# error <msg>
function error() {
    [ -z "$1" ] && exit 1
    notify-send "Error" "$1"
    echo_err "$1"
}

# echo_err <msg>
function echo_err() {
    [ -z "$1" ] && exit 1
    echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
}

function helpFunc() {
    echo "Usage: $(basename "$0") [options]

Option:
-h or --help                                Show this help message and exit
-v or --version                             Show version
-c or --connect                             Connect a screen
-d or --disconnect                          Disconnect a screen
-s or --status                              Show the status of the screen
-l or --list                                List all preset
-p or --preset <preset> [enable|disable]    Load a preset
--connected <primary|secondary|all>         Get the connected screen"
}

function checkDependencies() {
    for dependency in $dependencies; do
        ! command -v "$dependency" > /dev/null 2>&1 && \
            echo_err "Dependency \"$dependency\" not found" && exit 1
    done
}

# getConnectedScreen <primary|secondary|all> [ignore]
function getConnectedScreen() {
    [ -z "$1" ] && exit 1

    local scr=$(
        xrandr | \
        grep " connected"
    )

    case $1 in
        primary)
            scr=$(echo "$scr" | grep "primary");;
        secondary)
            scr=$(echo "$scr" | grep -v "primary");;
        all);;
        *)
            exit 1;;
    esac

    scr=$(echo "$scr" | awk '{print $1}')

    [ "$2" != "" ] && echo "$scr" | grep -vE "$2" || echo "$scr"
}

# getScreenMode <screen>
function getScreenMode() {
    [ -z "$1" ] && exit 1
    xrandr | \
        awk -v monitor="^$1 connected" '/connected/ {p = 0} $0 ~ monitor {p = 1} p' | \
        grep -v " connected" | \
        grep -oP '\d+x\d+'
}

function connectScreen() {
    local sideList="none\nright-of\nleft-of\nabove\nbelow\nsame-as" 
    local rotationList="none\nnormal\nleft\nright\ninverted"
    local commande="xrandr"

    local screens=$(getConnectedScreen all "$ignoreScreen")
    [ -z "$screens" ] && error "No screen found" && exit 1

    local screen=$(echo -e "$screens\n$presets" | rofi -dmenu -p "Connect a screen")
    [ -z "$screen" ] && exit 1

    if echo -e "$presets" | grep -q "$screen"; then
        $screen
        sleep 1
        info "Preset applied"
        i3-msg "restart"
        exit 0
    fi

    commande="$commande --output $screen"

    local modeList=$(getScreenMode "$screen")
    local mode=$(echo -e "auto\n$modeList" | rofi -dmenu -p "Choose mode")
    [ -z "$mode" ] && exit 1

    commande=$([ "$mode" != "auto" ] && echo "$commande --mode $mode" || echo "$commande --auto")

    local side=$(echo -e "$sideList"| rofi -dmenu -p "Choose side")
    [ -z "$side" ] && exit 1
    if [ "$side" != "none" ]; then
        local otherScreens=$(getConnectedScreen all "^$screen$")
        [ -z "$otherScreens" ] && exit 1

        local otherScreen=$(echo "$otherScreens" | rofi -dmenu -p "Screen side")
        [ -z "$otherScreen" ]  && exit 1

        commande="$commande --$side $otherScreen"
    fi

    local rotation=$(echo -e "$rotationList" | rofi -dmenu -p "Choose rotation")
    [ -z "$rotation" ] && exit 1
    [ "$rotation" != "none" ] && commande="$commande --rotate $rotation"

    ! $commande && error "Screen not connected" && exit 1

    sleep 1
    info "Screen connected" 
    i3-msg "restart"
}

function disconnectScreen() {
    local screens=$(getConnectedScreen all "$ignoreScreen")
    [ -z "$screens" ] && error "No screen found" && exit 1

    local screen=$(echo "$screens" | rofi -dmenu -p "Disconnect a screen")
    [ -z "$screen" ] && exit 1

    ! xrandr --output "$screen" --off && \
        error "Screen not disconnected" && exit 1

    sleep 1
    info "Screen disconnected"
    i3-msg "restart"
}

# loadPreset <preset> [enable|disable]
function loadPreset() {
    local preset="$1"
    [ -z "$preset" ] && exit 1

    ! echo -e "$presets" | grep -q "$preset" && \
        error "Preset not found" && exit 1

    $preset "$2" # execute the preset
    sleep 1
    info "Preset applied"
    i3-msg "restart"
}

# preset for work on laptop with 2 screens
# screenPresetWork [enable|disable]
function screenPresetWork() {
    local choosePreset="$1"
    local screens=$(getConnectedScreen all "$ignoreScreen")
    [ -z "$screens" ] && error "Preset : No screen found" && exit 1

    echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
        error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1

    if [ -z "$choosePreset" ]; then
        choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
    fi

    case $choosePreset in
        enable)
            xrandr --output DP1 --auto --right-of eDP1
            xrandr --output DP3 --auto --right-of DP1
            xrandr --output eDP1 --off;;
        disable)
            xrandr --output eDP1 --auto
            xrandr --output DP1 --off
            xrandr --output DP3 --off;;
        *)
            error "Preset : Unknown action" &&
            exit 1;;
    esac
}

# preset for main pc startup
# screenPresetStartup [enable|disable]
function screenPresetStartup() {
    local choosePreset="$1"
    local screens=$(getConnectedScreen all "$ignoreScreen")
    [ -z "$screens" ] && error "Preset : No screen found" && exit 1

    echo -e "$screens" | grep -Evq "DP-3|HDMI-1" && \
        error "Preset : Required screen \"eDP1, DP3\" not found" && exit 1

    if [ -z "$choosePreset" ]; then
        choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
    fi

    case $choosePreset in
        enable)
            xrandr --output DP-3 --mode 1920x1080 --primary
            xrandr --output HDMI-1 --mode 1366x768 --right-of DP-3;;
        disable)
            xrandr --output DP-3 --auto
            xrandr --output HDMI-1 --off;;
        *)
            error "Preset : Unknown action" &&
            exit 1;;
    esac
}

function main() {
    local action=0
    local param=""
    local presetName=""
    local enablePreset=""

    if [ $# -ge 1 ]; then
        for _ in $(seq 1 $#); do
            case $1 in
                -h | --help)
                    helpFunc
                    exit 0;;
                -v | --version)
                    echo "$version"
                    exit 0;;
                -c | --connect)
                    action=1;;
                -d | --disconnect)
                    action=2;;
                -s | --status)
                    action=3;;
                --connected)
                    action=4
                    param="$2"
                    shift;;
                -l | --list)
                    echo -e "$presets"
                    exit 0;;
                -p | --preset)
                    action=5
                    presetName="$2"
                    enablePreset="$3"
                    shift 2;;
                "");;
                *)
                    echo_err "Unknown parameter $1"
                    exit 1;;
            esac
            shift
        done
    fi

    case $action in
        1)
            connectScreen;;
        2)
            disconnectScreen;;
        3)
            xrandr --listmonitors;;
        4)
            getConnectedScreen "$param" "$ignoreScreen";;
        5)
            loadPreset "$presetName" "$enablePreset";;
        *)
            helpFunc
            exit 1;;
    esac
}

checkDependencies
main "$@"
