#!/bin/bash
# author : lordpax
# brightness v1.0

screen="eDP-1"
version="v1.0"

function helpFunc() {
    #function_body
    echo $"Usage : $0 <option>

Option :
-h or --help ...................................... Show help
-v or --version ................................... Show version
-i <num> .......................................... Increment brightness
-d <num> .......................................... Decrement brightness
-s <num> .......................................... Set brightness
-g ................................................ Get brightness
-G ................................................ Get brightness as a percentage"
    exit 0
}

# getBrightness [%]
function getBrightness() {
    local brightness=$(xrandr --verbose | grep Brightness | sed -e "s/.*: \([0-9]*\.[0-9]*\)/\1/g")
    [ "$1" == "%" ] && echo "$brightness * 100" | bc | cut -d '.' -f 1 || echo $brightness
}

# setBrightness <num>
function setBrightness() {
    [ "$1" == "" ] && echo "Parameter is needed" && exit 1
    xrandr --output $screen --brightness $1
}

# brightness <+|-> <num>
function brightness() {
    ([ "$1" == "" ] && [ "$2" == "" ]) && echo "Parameter is needed" && exit 1

    local brightness=$(getBrightness)
    local new=$(echo "$brightness $1 $2" | bc)
    setBrightness $new
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        case $1 in
            -h | --help)
                helpFunc;;
            -v | --version)
                echo $version;;
            -i)
                brightness + $2
                shift;;
            -d)
                brightness - $2
                shift;;
            -s)
                setBrightness $2
                shift;;
            -g)
                getBrightness;;
            -G)
                getBrightness %;;
            "")
                ;;
            *)
                echo $"Unknown parameter \"$1\""
                exit 1
        esac
        shift
    done
fi
