#!/bin/bash

firstPass=$(zenity --password --title="Mot de passe")
secondPass=$(zenity --password --title="Confirmation mot de passe")

if [ $firstPass == $secondPass ]; then
    aescrypt -e -p $firstPass $@ &> /dev/null && shred -zu $@ || zenity --error --text="Une erreur s'est produite" --title "Erreur"
else
    zenity --error --text="Les mots de passe sont différents" --title="Erreur"
fi

unset firstPass
unset secondPass
